[tool.poetry]
name = "incolume.py.fastapi.crud2"
version = "0.3.0"
description = ""
authors = ["Britodfbr <britodfbr@gmail.com>"]
license = "Unlicense"
readme = "README.md"
packages = [{include = "incolume"}]

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = {extras = ["all"], version = "^0.22.0"}
fastapi = {extras = ["all"], version = "^0.95.1"}


[tool.poetry.group.dev.dependencies]
pytest-cov = "^4.0.0"
pytest = "^7.3.1"
black = "^23.3.0"
taskipy = "^1.10.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
